version: '3.8'

services:
  backend:
    build: ./backend
    container_name: halloweengo-backend
    ports:
      - "5002:5002"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5002

  frontend:
    build: ./frontend
    container_name: halloweengo-frontend
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - backend
